name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Clear pip cache
      run: |
        rm -rf ~/.cache/pip

    - name: Upgrade pip and force reinstall numpy & matplotlib
      run: |
        python -m pip install --upgrade pip
        pip uninstall -y numpy matplotlib || true
        pip install numpy matplotlib

    - name: Install remaining dependencies
      run: |
        pip install -r requirements.txt

    - name: Debug numpy installation
      run: |
        python -c "import numpy; print('Numpy version:', numpy.__version__)"
        python -c "print('Numpy location:', numpy.__file__)"
        python -c "from numpy.linalg import inv; print('Import from numpy.linalg successful!')"

    - name: Run tests
      run: |
        pytest
